.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "MKTF" "1" "October 2020" "" ""
.
.SH "NAME"
\fBmktf\fR \- Launch a GCP Ubuntu instance and set up Terraform
.
.SH "SYNOPSIS"
.
.nf

mktf
     \-x, \-\-prefix NEW_RESOURCE_PREFIX (required)
     \-p, \-\-project PROJECT_ID         (required)
     \-z, \-\-zone ZONE                  (reguired)
     \-n, \-\-network NETWORK            (required)
    [\-t, \-\-machine\-type MACHINE_TYPE] (optional)
    [\-h, \-\-help]                      (optional)
    [\-s, \-\-random\-suffix]             (optional)
.
.fi
.
.SH "DESCRIPTION"
The mktf command creates an Ubuntu instance and installs Terraform\. The goal of this command is to make getting started with Terraform easier\.
.
.P
More specifically, mktf performs the tasks listed below\.
.
.IP "1." 4
Optionally creates a random suffix used for resource names\. and creates Terraform scripts for the Google Cloud provider,
.
.IP "2." 4
Creates a service account that will be used when creating the instance\.
.
.IP "3." 4
Creates a Google Cloud Storage bucket for holding Terraform state\.
.
.IP "4." 4
Creates a Google Cloud Ubuntu instance\.
.
.IP "5." 4
Installs Terraform on the instances\.
.
.IP "6." 4
Creates Terraform code files on the instance in /usr/local/etc/tf for the backend state, providers, regional providers, and so forth\.
.
.IP "7." 4
Modifies /etc/bash\.bashrc on the instance to notify a user upon login of the location of the Terraform files\.
.
.IP "8." 4
Modifies /etc/bash\.bashrc on the instance to set up \.virmrc if it does not already exist\.
.
.IP "" 0
.
.SH "OPTIONS"
.
.nf

 \-x, \-\-prefix NEW_RESOURCE_PREFIX (required)
    This option specifiesthe prefix for names of the resources created by mygcptf\.
    This includes the service account, the GCS bucket for Terraform state, and the instance\.
    This does not include resources created by Terraform\.

 \-p, \-\-project PROJECT_ID         (required)
    This option specifies the exiting project ID in which the resources will be created\.

 \-z, \-\-zone ZONE                  (reguired)
    This option specifies the zone in which the instance will be created\.

 \-n, \-\-network NETWORK            (required)
    This option specifies the name of an existing network to which the interface
    of the instance will be attached\.  This has only been tested for networks
    that have been created with automatic subnets\.

[\-t, \-\-machine\-type MACHINE_TYPE] (optional)
    This option specifies the machine type of the Ubuntu instance\.  The default is
    e2\-micro\.

[\-h, \-\-help]                      (optional)
    This option displays a help message

[\-s, \-\-random\-suffix]             (optional)
    This option appends a random suffix to each of the resources created by mktf\.
    This does not include the resources created within Terraform\.
.
.fi
.
.SH "SECURITY NOTES"
The service account that is created to launch the Terraform instance contains the permissions listed below\.
.
.IP "\(bu" 4
roles/owner
.
.IP "\(bu" 4
roles/resourcemanager\.projectIamAdmin
.
.IP "\(bu" 4
roles/iam\.serviceAccountUser
.
.IP "" 0
.
.SH "EXAMPLES"
.
.nf

\&\./mktf \-x my\-instance \-p my\-project \-n my\-network \-z us\-west2\-b \-s
.
.fi
.
.SH "COPYRIGHT"
mktf is copyright (c) 2020, Jeffrey S\. Levine\. Released under the Apache license\.
